### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by m-vollmer** [clintonboys/trendy-scraper#11]
I get the following error - any help would be appreciated

```
Traceback (most recent call last):
  File "gt_scraper_v2.py", line 145, in <module>
    stitch_frames(daily_frames, weekly_frame)
  File "gt_scraper_v2.py", line 126, in stitch_frames
    final_data_frame[0] = np.round(final_data_frame[0]/final_data_frame[0].max()*100,2)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
```

**Comment by TarmacD** [comment]
Hi

I got the same error. Could you fix the bug?

Thanks!

**Comment by tivoo** [comment]
Same over here. Has this project been abandoned?
