### ISSUE TITLE
TypeError in parse_csv

### ISSUE THREAD

**Issue by paulwohlfarth** [clintonboys/trendy-scraper#12]
Hi,
probably a small issue:

running 

`python gt_scraper_v2.py 2016-01-01 2017-02-18 donald trump`

gives the following:

`Traceback (most recent call last):
  File "gt_scraper_v2.py", line 149, in <module>
    daily_frames = get_daily_frames(start_date, end_date, keywords)
  File "gt_scraper_v2.py", line 92, in get_daily_frames
    frames.append(parse_csv(get_csv(resp_text)))
  File "gt_scraper_v2.py", line 71, in parse_csv
    lines = csv_contents.split('\n')
TypeError: a bytes-like object is required, not 'str'`

Any help is much appreciated!

**Comment by TarmacD** [comment]
Hello 

Change code line 67 to:

`lines = csv_contents.decode().split('\n')`

Failure occured probably because you use a newer python compiler version (than 2.7).

Greets CB93
