### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'columns'

### ISSUE THREAD

**Issue by rocket-pig** [clintonboys/trendy-scraper#4]
user@x230:~/projects/trendy-scraper$ python gt_scraper_v2.py  2017-02-01 2017-03-01 donald trump
No need to stitch; your time interval is short enough. 
Traceback (most recent call last):
  File "gt_scraper_v2.py", line 145, in <module>
    stitch_frames(daily_frames, weekly_frame)
  File "gt_scraper_v2.py", line 105, in stitch_frames
    weekly_frame.columns = ['Week_Start_Date', 'Weekly_Volume']
AttributeError: 'NoneType' object has no attribute 'columns'

I'll for sure help bugshoot more if need be.

**Comment by rocket-pig** [comment]
I fleshed this out. 'get_weekly_frame' func returns None when it believes time interval is short enough, causing the stitching at the end some confusion. easy enough, I just **commented out the if statement on line 94**:
```

def get_weekly_frame(start_date, end_date, keyword):

    #if datetime.strptime(start_date, '%Y-%m-%d') > datetime.strptime(end_date, '%Y-%m-%d') - timedelta(days=180):
    #    print('No need to stitch; your time interval is short enough. ')
    #    return None
    #else:
        resp_text = get_data(datetime.strptime(start_date, '%Y-%m-%d'), datetime.strptime(end_date, '%Y-%m-%d'), keyword)
        return parse_csv(get_csv(resp_text))

```
