### ISSUE TITLE
Error when running the program

### ISSUE THREAD

**Issue by cridom** [clintonboys/trendy-scraper#5]
I translated the python code to python 3 using 2to3 but I still get an error when running it. The problem is the following:

Traceback (most recent call last):
  File "gt_scraper_v2.py", line 143, in <module>
    daily_frames = get_daily_frames(start_date, end_date, keywords)
  File "gt_scraper_v2.py", line 85, in get_daily_frames
    frames.append(parse_csv(get_csv(resp_text)))
  File "gt_scraper_v2.py", line 64, in parse_csv
    lines = csv_contents.split('\n')
TypeError: a bytes-like object is required, not 'str'

Any Ideas?

**Comment by clintonboys** [comment]
Python 3 not supported.
