### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Koenson** [clintonboys/trendy-scraper#6]
Hi there!

I really like the potential of the tool and I'm trying to learn myself Python programming. However, I can't seem to find what's going wrong with the current code. 
I get this error >>
AttributeError: 'NoneType' object has no attribute 'columns'

Any thoughts? Could it be that the code is slightly out of date?

Thanks
Koen

CODE Snippet >

192:pythonpractice Koen$ python gt_scraper_v2.py 2017-10-01 2017-12-31 bitcoin
No need to stitch; your time interval is short enough. 
Traceback (most recent call last):
  File "gt_scraper_v2.py", line 145, in <module>
    stitch_frames(daily_frames, weekly_frame)
  File "gt_scraper_v2.py", line 105, in stitch_frames
    weekly_frame.columns = ['Week_Start_Date', 'Weekly_Volume']
AttributeError: 'NoneType' object has no attribute 'columns'

**Comment by AmitMY** [comment]
The issue is the `get_weekly_frame` returns `None` for ranges less than 180 days.
