### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by kkorovesis** [clintonboys/trendy-scraper#8]
Traceback (most recent call last):
  File "gt_scraper_v2.py", line 145, in <module>
    stitch_frames(daily_frames, weekly_frame)
  File "gt_scraper_v2.py", line 125, in stitch_frames
    final_data_frame = DataFrame.from_dict(final_data,orient='index').sort()
  File "/home/userfoo/anaconda2/envs/py27/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
(py27) userfoo:~/Github/trendy-scraper$

**Comment by AmitMY** [comment]
change to `sort_index`
